PY=python3

tests:
	$(PY) pairing_test.py
	$(PY) session_auth_test.py
	$(PY) session_comm_decrypt_test.py
	$(PY) session_comm_encrypt_test.py
	
pairing-test:
	$(PY) pairing_test.py
	
session-auth-test:
	$(PY) session_auth_test.py
	
session-comm-decrypt-test:
	$(PY) session_comm_decrypt_test.py
	
session-comm-encrypt-test:
	$(PY) session_comm_encrypt_test.py
