package u.scooters.attack.main

enum class RequestType {
    SCOOTERNAME, VOLTAGE, AMPERE, DISTANCE, SPEED, SUPERMASTER, SUPERBATTERY, LOCK, CRUISE, LIGHT, RECOVERY, BATTERYLIFE, NOCOUNT, DOWNGRADETOCLEAR, DOWNGRADETO5AA5
}